[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "aarch64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
version = 2

# Fail if ignored advisories don't exist (anymore).
unused-ignored-advisory = "deny"

ignore = []

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "MPL-2.0",
  "GPL-3.0-only",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-3.0",
]

[[licenses.clarify]]
name = "pkiprocmacros"
expression = "Apache-2.0 OR MIT"
license-files = []

[sources]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = ["wireapp"]
